apiVersion: v1
kind: Service
metadata:
  labels:
    app: autoscaler-hpa
    autoscaling.knative.dev/autoscaler-provider: hpa
    app.kubernetes.io/component: autoscaler-hpa
    app.kubernetes.io/name: knative-serving
    app.kubernetes.io/version: "1.3.2"
    serving.knative.dev/release: "v1.3.2"
    {{- include "knative-serving.labels" . | nindent 4 }}
  name: autoscaler-hpa
  namespace: knative-serving
spec:
  ports:
    # Define metrics and profiling for them to be accessible within service meshes.
  - name: http-metrics
    port: 9090
    targetPort: 9090
  - name: http-profiling
    port: 8008
    targetPort: 8008
  selector:
    app: autoscaler-hpa
    {{- include "knative-serving.selectorLabels" . | nindent 4 }}