apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "openfunction.fullname" . }}-manager-role
  labels:
  {{- include "openfunction.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - core.openfunction.io
    resources:
      - builders
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - core.openfunction.io
    resources:
      - builders/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - core.openfunction.io
    resources:
      - functions
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - core.openfunction.io
    resources:
      - functions/finalizers
    verbs:
      - update
  - apiGroups:
      - core.openfunction.io
    resources:
      - functions/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - core.openfunction.io
    resources:
      - servings
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - core.openfunction.io
    resources:
      - servings/finalizers
    verbs:
      - update
  - apiGroups:
      - core.openfunction.io
    resources:
      - servings/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - dapr.io
    resources:
      - components
      - subscriptions
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - events.k8s.io
    resources:
      - events
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - events.openfunction.io
    resources:
      - clustereventbus
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - events.openfunction.io
    resources:
      - clustereventbus/finalizers
    verbs:
      - update
  - apiGroups:
      - events.openfunction.io
    resources:
      - clustereventbus/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - events.openfunction.io
    resources:
      - clustereventbuses
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - events.openfunction.io
    resources:
      - clustereventbuses/finalizers
    verbs:
      - update
  - apiGroups:
      - events.openfunction.io
    resources:
      - clustereventbuses/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - events.openfunction.io
    resources:
      - eventbus
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - events.openfunction.io
    resources:
      - eventbus/finalizers
    verbs:
      - update
  - apiGroups:
      - events.openfunction.io
    resources:
      - eventbus/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - events.openfunction.io
    resources:
      - eventbuses
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - events.openfunction.io
    resources:
      - eventbuses/finalizers
    verbs:
      - update
  - apiGroups:
      - events.openfunction.io
    resources:
      - eventbuses/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - events.openfunction.io
    resources:
      - eventsources
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - events.openfunction.io
    resources:
      - eventsources/finalizers
    verbs:
      - update
  - apiGroups:
      - events.openfunction.io
    resources:
      - eventsources/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - events.openfunction.io
    resources:
      - triggers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - events.openfunction.io
    resources:
      - triggers/finalizers
    verbs:
      - update
  - apiGroups:
      - events.openfunction.io
    resources:
      - triggers/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - gateway.networking.k8s.io
    resources:
      - gateways
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - gateway.networking.k8s.io
    resources:
      - gateways/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - gateway.networking.k8s.io
    resources:
      - httproutes
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - http.keda.sh
    resources:
      - httpscaledobjects
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - keda.sh
    resources:
      - scaledjobs
      - scaledobjects
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - networking.openfunction.io
    resources:
      - gateways
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - networking.openfunction.io
    resources:
      - gateways/finalizers
    verbs:
      - update
  - apiGroups:
      - networking.openfunction.io
    resources:
      - gateways/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - serving.knative.dev
    resources:
      - services
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - shipwright.io
    resources:
      - buildruns
      - builds
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "openfunction.fullname" . }}-manager-rolebinding
  labels:
  {{- include "openfunction.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "openfunction.fullname" . }}-manager-role'
subjects:
  - kind: ServiceAccount
    name: '{{ include "openfunction.fullname" . }}-controller-manager'
    namespace: '{{ .Release.Namespace }}'