apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: builders.core.openfunction.io
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUROVENDQWgyZ0F3SUJBZ0lVUWNCUGt6MC90OTZ2dzJZV2F0S1JqRWZwaFJrd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0tqRW9NQ1lHQTFVRUF3d2ZZMkV0YjNCbGJtWjFibU4wYVc5dUxYZGxZbWh2YjJzdGMyVnlkbWxqWlRBZQpGdzB5TWpBME1EY3dNelV3TURaYUZ3MHpNakEwTURRd016VXdNRFphTUNveEtEQW1CZ05WQkFNTUgyTmhMVzl3ClpXNW1kVzVqZEdsdmJpMTNaV0pvYjI5ckxYTmxjblpwWTJVd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFEVXpZK1hZSmoxdS9sNmZvR1NiWEhaUDNhZklZN1lFRi9ZUk9sQ1V0Q2VBZ25CSDE4NwpqUk1hUVlTWmxMQTBBNEUxR0ZONzVqUU5KV3k5MVJkZmsxN1Z3RFlSa2lpUmg4bjNJbHpsbHQrQ3JKdWJsUHJmCkRFUVZuUkNTRW1Udnc5WmIvWkpXSXloRTNmN0dhckY4S3R3VVZXazNzTzB2Mk0wWXVvdGQxdjdUV3JmS0FBaUgKQjhNS0E2VTN6M0gyOSs0M1NkN1I5SW8vQzhuSFVHMkUrMDk5R3lhcnhRNUVkb2hkTkVCc05jbGprS0ZkNDRkKwpTdzRSVG56MFhIS1JILy9TM0hQMmUvd1ptRTBkb2E0N2VXdlVBay8waUxtMnY3Wk1CWUF2TmFDamVOd3BNNjJmCmpBVnd2YVBid0lIRGZBZHdRaU42bHhrbThIWHlsV0xEZDVnTEFnTUJBQUdqVXpCUk1CMEdBMVVkRGdRV0JCVEYKL0VFcGdsVGJOZ1VTYnhTS2c1bk1kMzMyZ3pBZkJnTlZIU01FR0RBV2dCVEYvRUVwZ2xUYk5nVVNieFNLZzVuTQpkMzMyZ3pBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFCWTN5MWI0MC9sCm03bVJrek91YnRFSnNYWWUzYTFSYkx0eE4vNnQzOG1kNnlneWxVVzZ5WWxJTHBYdjc1ZlFIR3Z2cUhMREdJdmMKOG5VVCsrNUgrUHExaHZxeVV3azFUby9NODE2NkNDMHB2UVNERERMMkNYUzl5TWtrL25tQXBTV2l5aVhRT0cxRApyWEdSMk9BZFlYcFdaNHlzZFRqSGNCY2V1Z3Y0ZzJGOWtXSXJ1eDBCeExGdzE4YjVqSGI1dTltK1VnMDZZMTd6ClNxbWhza0dYajVLWTkwWXAwZUpnUHBWRjNPSzhIWGRYbVlTcjdjOXp4bWc1NGR4K0QxcnMveUc1SjJBN1NTU3gKM1BnL05zbXZvY2QzdFp3K1ZyUnkycC9GbXZ4aUdQOHM0MFBQMTVjdkZMcnM0REVZRFVtekxXNmtqVW9aK041bgpiZFFGM24rZ045ZnkKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
        service:
          name: openfunction-webhook-service
          namespace: openfunction
          path: /convert
      conversionReviewVersions:
        - v1
  group: core.openfunction.io
  names:
    kind: Builder
    listKind: BuilderList
    plural: builders
    shortNames:
      - fb
    singular: builder
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - jsonPath: .status.phase
          name: Phase
          type: string
        - jsonPath: .status.state
          name: State
          type: string
        - jsonPath: .status.reason
          name: Reason
          type: string
        - jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
      name: v1beta1
      schema:
        openAPIV3Schema:
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              properties:
                builder:
                  type: string
                builderCredentials:
                  properties:
                    name:
                      type: string
                  type: object
                  x-kubernetes-map-type: atomic
                dockerfile:
                  type: string
                env:
                  additionalProperties:
                    type: string
                  type: object
                image:
                  type: string
                imageCredentials:
                  properties:
                    name:
                      type: string
                  type: object
                  x-kubernetes-map-type: atomic
                params:
                  additionalProperties:
                    type: string
                  type: object
                port:
                  format: int32
                  type: integer
                shipwright:
                  properties:
                    strategy:
                      properties:
                        kind:
                          type: string
                        name:
                          type: string
                      required:
                        - name
                      type: object
                    timeout:
                      format: duration
                      type: string
                  type: object
                srcRepo:
                  properties:
                    bundleContainer:
                      properties:
                        image:
                          type: string
                      required:
                        - image
                      type: object
                    credentials:
                      properties:
                        name:
                          type: string
                      type: object
                      x-kubernetes-map-type: atomic
                    revision:
                      type: string
                    sourceSubPath:
                      type: string
                    url:
                      type: string
                  type: object
                state:
                  type: string
                timeout:
                  type: string
              required:
                - image
                - srcRepo
              type: object
            status:
              properties:
                output:
                  properties:
                    digest:
                      type: string
                    size:
                      format: int64
                      type: integer
                  type: object
                phase:
                  type: string
                reason:
                  type: string
                resourceRef:
                  additionalProperties:
                    type: string
                  type: object
                sources:
                  items:
                    properties:
                      bundle:
                        properties:
                          digest:
                            type: string
                        type: object
                      git:
                        properties:
                          branchName:
                            type: string
                          commitAuthor:
                            type: string
                          commitSha:
                            type: string
                        type: object
                      name:
                        type: string
                    required:
                      - name
                    type: object
                  type: array
                state:
                  type: string
              type: object
          type: object
      served: true
      storage: false
      subresources:
        status: {}
    - additionalPrinterColumns:
        - jsonPath: .status.phase
          name: Phase
          type: string
        - jsonPath: .status.state
          name: State
          type: string
        - jsonPath: .status.reason
          name: Reason
          type: string
        - jsonPath: .status.buildDuration
          name: BuildDuration
          type: string
        - jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
      name: v1beta2
      schema:
        openAPIV3Schema:
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              properties:
                builder:
                  type: string
                builderCredentials:
                  properties:
                    name:
                      type: string
                  type: object
                  x-kubernetes-map-type: atomic
                builderMaxAge:
                  type: string
                dockerfile:
                  type: string
                env:
                  additionalProperties:
                    type: string
                  type: object
                failedBuildsHistoryLimit:
                  format: int32
                  type: integer
                image:
                  type: string
                imageCredentials:
                  properties:
                    name:
                      type: string
                  type: object
                  x-kubernetes-map-type: atomic
                shipwright:
                  properties:
                    params:
                      items:
                        properties:
                          configMapValue:
                            properties:
                              format:
                                type: string
                              key:
                                type: string
                              name:
                                type: string
                            required:
                              - key
                              - name
                            type: object
                          name:
                            type: string
                          secretValue:
                            properties:
                              format:
                                type: string
                              key:
                                type: string
                              name:
                                type: string
                            required:
                              - key
                              - name
                            type: object
                          value:
                            type: string
                          values:
                            items:
                              properties:
                                configMapValue:
                                  properties:
                                    format:
                                      type: string
                                    key:
                                      type: string
                                    name:
                                      type: string
                                  required:
                                    - key
                                    - name
                                  type: object
                                secretValue:
                                  properties:
                                    format:
                                      type: string
                                    key:
                                      type: string
                                    name:
                                      type: string
                                  required:
                                    - key
                                    - name
                                  type: object
                                value:
                                  type: string
                              type: object
                            type: array
                        required:
                          - name
                        type: object
                      type: array
                    strategy:
                      properties:
                        kind:
                          type: string
                        name:
                          type: string
                      required:
                        - name
                      type: object
                    timeout:
                      format: duration
                      type: string
                  type: object
                srcRepo:
                  properties:
                    bundleContainer:
                      properties:
                        image:
                          type: string
                      required:
                        - image
                      type: object
                    credentials:
                      properties:
                        name:
                          type: string
                      type: object
                      x-kubernetes-map-type: atomic
                    revision:
                      type: string
                    sourceSubPath:
                      type: string
                    url:
                      type: string
                  type: object
                state:
                  type: string
                successfulBuildsHistoryLimit:
                  format: int32
                  type: integer
                timeout:
                  type: string
              required:
                - image
                - srcRepo
              type: object
            status:
              properties:
                buildDuration:
                  type: string
                message:
                  type: string
                output:
                  properties:
                    digest:
                      type: string
                    size:
                      format: int64
                      type: integer
                  type: object
                phase:
                  type: string
                reason:
                  type: string
                resourceRef:
                  additionalProperties:
                    type: string
                  type: object
                sources:
                  items:
                    properties:
                      bundle:
                        properties:
                          digest:
                            type: string
                        type: object
                      git:
                        properties:
                          branchName:
                            type: string
                          commitAuthor:
                            type: string
                          commitSha:
                            type: string
                        type: object
                      name:
                        type: string
                    required:
                      - name
                    type: object
                  type: array
                state:
                  type: string
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []