apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: eventsources.events.openfunction.io
spec:
  group: events.openfunction.io
  names:
    kind: EventSource
    listKind: EventSourceList
    plural: eventsources
    shortNames:
      - es
    singular: eventsource
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - jsonPath: .spec.eventBus
          name: EventBus
          type: string
        - jsonPath: .spec.sink.uri
          name: Sink
          type: string
        - jsonPath: .status.conditions[-1].type
          name: Status
          type: string
      name: v1alpha1
      schema:
        openAPIV3Schema:
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              properties:
                build:
                  properties:
                    builder:
                      type: string
                    builderCredentials:
                      properties:
                        name:
                          type: string
                      type: object
                      x-kubernetes-map-type: atomic
                    builderMaxAge:
                      type: string
                    dockerfile:
                      type: string
                    env:
                      additionalProperties:
                        type: string
                      type: object
                    failedBuildsHistoryLimit:
                      format: int32
                      type: integer
                    params:
                      additionalProperties:
                        type: string
                      type: object
                    shipwright:
                      properties:
                        strategy:
                          properties:
                            kind:
                              type: string
                            name:
                              type: string
                          required:
                            - name
                          type: object
                        timeout:
                          format: duration
                          type: string
                      type: object
                    srcRepo:
                      properties:
                        bundleContainer:
                          properties:
                            image:
                              type: string
                          required:
                            - image
                          type: object
                        credentials:
                          properties:
                            name:
                              type: string
                          type: object
                          x-kubernetes-map-type: atomic
                        revision:
                          type: string
                        sourceSubPath:
                          type: string
                        url:
                          type: string
                      type: object
                    successfulBuildsHistoryLimit:
                      format: int32
                      type: integer
                    timeout:
                      type: string
                  required:
                    - srcRepo
                  type: object
                cron:
                  additionalProperties:
                    properties:
                      schedule:
                        type: string
                    required:
                      - schedule
                    type: object
                  type: object
                eventBus:
                  type: string
                kafka:
                  additionalProperties:
                    properties:
                      authRequired:
                        type: boolean
                      brokers:
                        type: string
                      maxMessageBytes:
                        format: int64
                        type: integer
                      saslPassword:
                        type: string
                      saslUsername:
                        type: string
                      scaleOption:
                        properties:
                          advanced:
                            properties:
                              horizontalPodAutoscalerConfig:
                                properties:
                                  behavior:
                                    properties:
                                      scaleDown:
                                        properties:
                                          policies:
                                            items:
                                              properties:
                                                periodSeconds:
                                                  format: int32
                                                  type: integer
                                                type:
                                                  type: string
                                                value:
                                                  format: int32
                                                  type: integer
                                              required:
                                                - periodSeconds
                                                - type
                                                - value
                                              type: object
                                            type: array
                                            x-kubernetes-list-type: atomic
                                          selectPolicy:
                                            type: string
                                          stabilizationWindowSeconds:
                                            format: int32
                                            type: integer
                                        type: object
                                      scaleUp:
                                        properties:
                                          policies:
                                            items:
                                              properties:
                                                periodSeconds:
                                                  format: int32
                                                  type: integer
                                                type:
                                                  type: string
                                                value:
                                                  format: int32
                                                  type: integer
                                              required:
                                                - periodSeconds
                                                - type
                                                - value
                                              type: object
                                            type: array
                                            x-kubernetes-list-type: atomic
                                          selectPolicy:
                                            type: string
                                          stabilizationWindowSeconds:
                                            format: int32
                                            type: integer
                                        type: object
                                    type: object
                                  name:
                                    type: string
                                type: object
                              restoreToOriginalReplicaCount:
                                type: boolean
                            type: object
                          authRef:
                            properties:
                              kind:
                                type: string
                              name:
                                type: string
                            required:
                              - name
                            type: object
                          consumerGroup:
                            type: string
                          cooldownPeriod:
                            format: int32
                            type: integer
                          lagThreshold:
                            type: string
                          maxReplicaCount:
                            format: int32
                            type: integer
                          metadata:
                            additionalProperties:
                              type: string
                            type: object
                          minReplicaCount:
                            format: int32
                            type: integer
                          pollingInterval:
                            format: int32
                            type: integer
                          topic:
                            type: string
                        required:
                          - lagThreshold
                        type: object
                      topic:
                        type: string
                    required:
                      - authRequired
                      - brokers
                    type: object
                  type: object
                logLevel:
                  type: string
                mqtt:
                  additionalProperties:
                    properties:
                      caCert:
                        type: string
                      cleanSession:
                        type: boolean
                      clientCert:
                        type: string
                      clientKey:
                        type: string
                      consumerID:
                        type: string
                      qos:
                        format: int64
                        type: integer
                      retain:
                        type: boolean
                      topic:
                        type: string
                      url:
                        type: string
                    required:
                      - topic
                      - url
                    type: object
                  type: object
                redis:
                  additionalProperties:
                    properties:
                      dialTimeout:
                        type: string
                      enableTLS:
                        type: boolean
                      failover:
                        type: boolean
                      idleCheckFrequency:
                        type: string
                      idleTimeout:
                        type: string
                      maxConnAge:
                        type: string
                      minIdleConns:
                        format: int64
                        type: integer
                      poolSize:
                        format: int64
                        type: integer
                      poolTimeout:
                        type: string
                      processingTimeout:
                        type: string
                      readTimeout:
                        type: string
                      redeliverInterval:
                        type: string
                      redisDB:
                        format: int64
                        type: integer
                      redisHost:
                        type: string
                      redisMaxRetries:
                        format: int64
                        type: integer
                      redisMaxRetryInterval:
                        type: string
                      redisMinRetryInterval:
                        type: string
                      redisPassword:
                        type: string
                      redisType:
                        type: string
                      sentinelMasterName:
                        type: string
                      writeTimeout:
                        type: string
                    required:
                      - redisHost
                      - redisPassword
                    type: object
                  type: object
                sink:
                  properties:
                    ref:
                      properties:
                        apiVersion:
                          type: string
                        kind:
                          type: string
                        name:
                          type: string
                        namespace:
                          type: string
                      required:
                        - apiVersion
                        - kind
                        - name
                      type: object
                    uri:
                      type: string
                  type: object
              type: object
            status:
              properties:
                conditions:
                  items:
                    properties:
                      message:
                        type: string
                      reason:
                        enum:
                          - EventSourceFunctionCreated
                          - ErrorCreatingEventSource
                          - ErrorCreatingEventSourceFunction
                          - EventSourceIsReady
                          - ErrorConfiguration
                          - ErrorToFindExistEventBus
                          - ErrorGenerateComponent
                          - ErrorGenerateScaledObject
                          - PendingCreation
                          - ErrorToFindTriggerSubscribers
                          - ErrorCreatingTrigger
                          - TriggerIsReady
                          - ErrorCreatingTriggerFunction
                          - TriggerFunctionCreated
                        type: string
                      status:
                        type: string
                      timestamp:
                        type: string
                      type:
                        enum:
                          - Created
                          - Error
                          - Pending
                          - Unknown
                          - Terminating
                          - Terminated
                          - Ready
                        type: string
                    required:
                      - status
                      - type
                    type: object
                  type: array
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []