apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: eventbuses.events.openfunction.io
spec:
  group: events.openfunction.io
  names:
    kind: EventBus
    listKind: EventBusList
    plural: eventbuses
    shortNames:
      - eb
    singular: eventbus
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              properties:
                natsStreaming:
                  properties:
                    ackWaitTime:
                      type: string
                    consumerID:
                      type: string
                    deliverAll:
                      type: boolean
                    deliverNew:
                      type: boolean
                    durableSubscriptionName:
                      type: string
                    maxInFlight:
                      format: int64
                      type: integer
                    natsStreamingClusterID:
                      type: string
                    natsURL:
                      type: string
                    scaleOption:
                      properties:
                        advanced:
                          properties:
                            horizontalPodAutoscalerConfig:
                              properties:
                                behavior:
                                  properties:
                                    scaleDown:
                                      properties:
                                        policies:
                                          items:
                                            properties:
                                              periodSeconds:
                                                format: int32
                                                type: integer
                                              type:
                                                type: string
                                              value:
                                                format: int32
                                                type: integer
                                            required:
                                              - periodSeconds
                                              - type
                                              - value
                                            type: object
                                          type: array
                                          x-kubernetes-list-type: atomic
                                        selectPolicy:
                                          type: string
                                        stabilizationWindowSeconds:
                                          format: int32
                                          type: integer
                                      type: object
                                    scaleUp:
                                      properties:
                                        policies:
                                          items:
                                            properties:
                                              periodSeconds:
                                                format: int32
                                                type: integer
                                              type:
                                                type: string
                                              value:
                                                format: int32
                                                type: integer
                                            required:
                                              - periodSeconds
                                              - type
                                              - value
                                            type: object
                                          type: array
                                          x-kubernetes-list-type: atomic
                                        selectPolicy:
                                          type: string
                                        stabilizationWindowSeconds:
                                          format: int32
                                          type: integer
                                      type: object
                                  type: object
                                name:
                                  type: string
                              type: object
                            restoreToOriginalReplicaCount:
                              type: boolean
                          type: object
                        authRef:
                          properties:
                            kind:
                              type: string
                            name:
                              type: string
                          required:
                            - name
                          type: object
                        cooldownPeriod:
                          format: int32
                          type: integer
                        durableName:
                          type: string
                        lagThreshold:
                          type: string
                        maxReplicaCount:
                          format: int32
                          type: integer
                        metadata:
                          additionalProperties:
                            type: string
                          type: object
                        minReplicaCount:
                          format: int32
                          type: integer
                        natsServerMonitoringEndpoint:
                          type: string
                        pollingInterval:
                          format: int32
                          type: integer
                        queueGroup:
                          type: string
                        subject:
                          type: string
                      required:
                        - lagThreshold
                        - natsServerMonitoringEndpoint
                      type: object
                    startAtSequence:
                      format: int64
                      type: integer
                    startAtTime:
                      type: string
                    startAtTimeDelta:
                      type: string
                    startAtTimeFormat:
                      type: string
                    startWithLastReceived:
                      type: boolean
                    subscriptionType:
                      type: string
                  required:
                    - durableSubscriptionName
                    - natsStreamingClusterID
                    - natsURL
                    - subscriptionType
                  type: object
                topic:
                  type: string
              type: object
          type: object
      served: true
      storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []