apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: gateways.networking.openfunction.io
spec:
  group: networking.openfunction.io
  names:
    kind: Gateway
    listKind: GatewayList
    plural: gateways
    singular: gateway
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - jsonPath: .status.addresses[*].value
          name: Address
          type: string
        - jsonPath: .status.conditions[?(@.type=="Ready")].status
          name: Ready
          type: string
        - jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
      name: v1alpha1
      schema:
        openAPIV3Schema:
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              properties:
                clusterDomain:
                  default: cluster.local
                  type: string
                domain:
                  type: string
                gatewayDef:
                  properties:
                    gatewayClassName:
                      maxLength: 253
                      minLength: 1
                      type: string
                    name:
                      maxLength: 253
                      minLength: 1
                      type: string
                    namespace:
                      maxLength: 63
                      minLength: 1
                      pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?$
                      type: string
                  required:
                    - gatewayClassName
                    - namespace
                  type: object
                gatewayRef:
                  properties:
                    name:
                      maxLength: 253
                      minLength: 1
                      type: string
                    namespace:
                      maxLength: 63
                      minLength: 1
                      pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?$
                      type: string
                  required:
                    - name
                    - namespace
                  type: object
                gatewaySpec:
                  properties:
                    listeners:
                      items:
                        properties:
                          allowedRoutes:
                            default:
                              namespaces:
                                from: Same
                            properties:
                              kinds:
                                items:
                                  properties:
                                    group:
                                      default: gateway.networking.k8s.io
                                      maxLength: 253
                                      pattern: ^$|^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$
                                      type: string
                                    kind:
                                      maxLength: 63
                                      minLength: 1
                                      pattern: ^[a-zA-Z]([-a-zA-Z0-9]*[a-zA-Z0-9])?$
                                      type: string
                                  required:
                                    - kind
                                  type: object
                                maxItems: 8
                                type: array
                              namespaces:
                                default:
                                  from: Same
                                properties:
                                  from:
                                    default: Same
                                    enum:
                                      - All
                                      - Selector
                                      - Same
                                    type: string
                                  selector:
                                    properties:
                                      matchExpressions:
                                        items:
                                          properties:
                                            key:
                                              type: string
                                            operator:
                                              type: string
                                            values:
                                              items:
                                                type: string
                                              type: array
                                          required:
                                            - key
                                            - operator
                                          type: object
                                        type: array
                                      matchLabels:
                                        additionalProperties:
                                          type: string
                                        type: object
                                    type: object
                                    x-kubernetes-map-type: atomic
                                type: object
                            type: object
                          hostname:
                            maxLength: 253
                            minLength: 1
                            pattern: ^(\*\.)?[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$
                            type: string
                          name:
                            maxLength: 253
                            minLength: 1
                            pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$
                            type: string
                          port:
                            format: int32
                            maximum: 65535
                            minimum: 1
                            type: integer
                          protocol:
                            maxLength: 255
                            minLength: 1
                            pattern: ^[a-zA-Z0-9]([-a-zSA-Z0-9]*[a-zA-Z0-9])?$|[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*\/[A-Za-z0-9]+$
                            type: string
                          tls:
                            properties:
                              certificateRefs:
                                items:
                                  properties:
                                    group:
                                      default: ""
                                      maxLength: 253
                                      pattern: ^$|^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$
                                      type: string
                                    kind:
                                      default: Secret
                                      maxLength: 63
                                      minLength: 1
                                      pattern: ^[a-zA-Z]([-a-zA-Z0-9]*[a-zA-Z0-9])?$
                                      type: string
                                    name:
                                      maxLength: 253
                                      minLength: 1
                                      type: string
                                    namespace:
                                      maxLength: 63
                                      minLength: 1
                                      pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?$
                                      type: string
                                  required:
                                    - name
                                  type: object
                                maxItems: 64
                                type: array
                              mode:
                                default: Terminate
                                enum:
                                  - Terminate
                                  - Passthrough
                                type: string
                              options:
                                additionalProperties:
                                  maxLength: 4096
                                  minLength: 0
                                  type: string
                                maxProperties: 16
                                type: object
                            type: object
                        required:
                          - name
                          - port
                          - protocol
                        type: object
                      minItems: 1
                      type: array
                      x-kubernetes-list-map-keys:
                        - name
                      x-kubernetes-list-type: map
                  required:
                    - listeners
                  type: object
                hostTemplate:
                  default: '{{.Name}}.{{.Namespace}}.{{.Domain}}'
                  type: string
                httpRouteLabelKey:
                  default: app.kubernetes.io/managed-by
                  type: string
                pathTemplate:
                  default: '{{.Namespace}}/{{.Name}}'
                  type: string
              required:
                - domain
                - gatewaySpec
              type: object
            status:
              properties:
                addresses:
                  items:
                    properties:
                      type:
                        default: IPAddress
                        enum:
                          - IPAddress
                          - Hostname
                          - NamedAddress
                        type: string
                      value:
                        maxLength: 253
                        minLength: 1
                        type: string
                    required:
                      - value
                    type: object
                  maxItems: 16
                  type: array
                conditions:
                  default:
                    - message: Waiting for controller
                      reason: NotReconciled
                      status: Unknown
                      type: Scheduled
                  items:
                    properties:
                      message:
                        type: string
                      reason:
                        type: string
                      status:
                        type: string
                      type:
                        type: string
                    required:
                      - message
                      - reason
                      - status
                      - type
                    type: object
                  maxItems: 8
                  type: array
                  x-kubernetes-list-map-keys:
                    - type
                  x-kubernetes-list-type: map
                listeners:
                  items:
                    properties:
                      attachedRoutes:
                        format: int32
                        type: integer
                      conditions:
                        items:
                          properties:
                            message:
                              type: string
                            reason:
                              type: string
                            status:
                              type: string
                            type:
                              type: string
                          required:
                            - message
                            - reason
                            - status
                            - type
                          type: object
                        maxItems: 8
                        type: array
                        x-kubernetes-list-map-keys:
                          - type
                        x-kubernetes-list-type: map
                      name:
                        maxLength: 253
                        minLength: 1
                        pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$
                        type: string
                      supportedKinds:
                        items:
                          properties:
                            group:
                              default: gateway.networking.k8s.io
                              maxLength: 253
                              pattern: ^$|^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$
                              type: string
                            kind:
                              maxLength: 63
                              minLength: 1
                              pattern: ^[a-zA-Z]([-a-zA-Z0-9]*[a-zA-Z0-9])?$
                              type: string
                          required:
                            - kind
                          type: object
                        maxItems: 8
                        type: array
                    required:
                      - attachedRoutes
                      - conditions
                      - name
                      - supportedKinds
                    type: object
                  maxItems: 64
                  type: array
                  x-kubernetes-list-map-keys:
                    - name
                  x-kubernetes-list-type: map
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []